import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner'

import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider appearance={{baseTheme: dark}}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          
        <ThemeProvider
            attribute="class"
            forcedTheme='dark'
            defaultTheme="system"
            storageKey='streamhive-theme'
            enableSystem
            disableTransitionOnChange
          >
          <Toaster theme="light" position="bottom-center"/>
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}